# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZoEKjruNpFdMahGvkWx52_tEmN6VK_M
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# App title
st.title("💳 Real-Time Credit Card Fraud Detection")

# Upload CSV
uploaded_file = st.file_uploader("Upload your credit card transaction CSV", type="csv")

if uploaded_file is not None:
    # Read and show data
    df = pd.read_csv(uploaded_file)
    st.write("### Sample Data", df.head())

    # Drop rows with missing class or amount
    df.dropna(subset=["Class", "Amount"], inplace=True)

    # Features and labels
    X = df.drop(columns=["Class"])
    y = df["Class"]

    # Scale
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Train Isolation Forest
    model = IsolationForest(contamination=0.001, random_state=42)
    model.fit(X_scaled)

    # Predict
    df["Prediction"] = model.predict(X_scaled)
    df["Prediction"] = df["Prediction"].apply(lambda x: 1 if x == -1 else 0)

    # Show results
    st.write("### Prediction Summary")
    st.write(df[["Amount", "Class", "Prediction"]].head(10))

    # Fraud count
    fraud_count = df["Prediction"].sum()
    st.success(f"🚨 {fraud_count} suspected fraudulent transactions detected.")

    # Optional download
    st.download_button("Download Results CSV", data=df.to_csv(index=False), file_name="fraud_results.csv")
else:
    st.info("Upload a CSV file to begin.")